# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2011-2022 ETH Zurich.

status = ["check-license-headers", "build-and-test-client - macos-latest", "build-and-test-client - ubuntu-latest", "build-and-test-client - windows-latest"]
timeout_sec = 7200
